'use strict';

const test = require('node:test');
const assert = require('node:assert');
const path = require('path');

const { loadInstructionSet } = require('../src/instructions');
const { parseLine, analyzeLine, analyzeDocument } = require('../src/analyze');

const set = loadInstructionSet(path.join(__dirname, 'fixtures', 'instructions.fixture.json'));

/** Analyze one line and return its issue codes, in order. */
const codes = (line, options) => analyzeLine(line, set, options).map((i) => i.code);
const only = (line, options) => {
  const issues = analyzeLine(line, set, options);
  assert.equal(issues.length, 1, `expected exactly one issue for ${JSON.stringify(line)}`);
  return issues[0];
};

test('accepts a well-formed call', () => {
  assert.deepEqual(codes('FixMove(10, 20)'), []);
  assert.deepEqual(codes('FixMove(10,20)'), []);
  assert.deepEqual(codes('  FixMove( -12.5 , 0 )  '), []);
});

test('accepts an instruction that takes no arguments', () => {
  assert.deepEqual(codes('FixStop()'), []);
});

test('blank lines produce no issues', () => {
  assert.deepEqual(codes(''), []);
  assert.deepEqual(codes('    '), []);
  assert.deepEqual(codes('\t'), []);
});

test('comments produce no issues', () => {
  assert.deepEqual(codes('// Program generated by RoboDK'), []);
  assert.deepEqual(codes('   // indented comment'), []);
  assert.deepEqual(codes('FixStop() // trailing comment'), []);
});

test('unknown instruction is a warning, never an error', () => {
  const issue = only('NotAnInstruction(1)');
  assert.equal(issue.code, 'unknown-instruction');
  assert.equal(issue.severity, 'warning');
  assert.match(issue.message, /0\.0-fixture/);
});

test('unknown instruction can be silenced', () => {
  assert.deepEqual(codes('NotAnInstruction(1)', { unknownInstruction: 'off' }), []);
});

test('a name differing only by case is accepted, not flagged', () => {
  // The robot resolves instruction names regardless of case: SetWRF and SetWrf
  // both work, so neither may be reported as a problem.
  assert.deepEqual(codes('fixmove(1, 2)'), []);
  assert.deepEqual(codes('FIXMOVE(1, 2)'), []);
  assert.deepEqual(codes('FixMOVE(1, 2)'), []);
});

test('a case variant is still validated against its instruction', () => {
  assert.deepEqual(codes('fixmove(1)'), ['arg-count']);
  assert.deepEqual(codes('FIXCOUNT(2.5)'), ['expected-int']);
  assert.deepEqual(codes('fixmove(101, 0)'), ['out-of-range']);
});

test('wrong argument count is an error that shows the signature', () => {
  const tooFew = only('FixMove(1)');
  assert.equal(tooFew.code, 'arg-count');
  assert.equal(tooFew.severity, 'error');
  assert.match(tooFew.message, /takes 2 arguments, got 1/);
  assert.match(tooFew.message, /FixMove\(x: number mm, y: number mm\)/);

  assert.deepEqual(codes('FixMove(1, 2, 3)'), ['arg-count']);
  assert.deepEqual(codes('FixStop(1)'), ['arg-count']);
  assert.match(only('FixCount()').message, /takes 1 argument,/);
});

test('non-numeric argument is an error', () => {
  const issue = only('FixMove(abc, 2)');
  assert.equal(issue.code, 'not-a-number');
  assert.equal(issue.severity, 'error');
});

test('scientific notation is rejected with its own message', () => {
  const issue = only('FixMove(1e3, 2)');
  assert.equal(issue.code, 'scientific-notation');
  assert.equal(issue.severity, 'error');
});

test('a parameter typed int rejects a fractional value', () => {
  const issue = only('FixCount(2.5)');
  assert.equal(issue.code, 'expected-int');
  assert.equal(issue.severity, 'error');
  // A whole number written with a decimal point is still an integer.
  assert.deepEqual(codes('FixCount(2.0)'), []);
});

test('a parameter typed bool accepts only 0 and 1', () => {
  assert.deepEqual(codes('FixEnable(0)'), []);
  assert.deepEqual(codes('FixEnable(1)'), []);
  assert.deepEqual(codes('FixEnable(2)'), ['expected-bool']);
});

test('exceeding min or max is a warning, not an error', () => {
  const over = only('FixMove(101, 0)');
  assert.equal(over.code, 'out-of-range');
  assert.equal(over.severity, 'warning');
  assert.match(over.message, /maximum 100 mm/);

  const under = only('FixMove(-101, 0)');
  assert.equal(under.code, 'out-of-range');
  assert.match(under.message, /minimum -100 mm/);

  assert.deepEqual(codes('FixMove(100, 0)'), []);
  assert.deepEqual(codes('FixMove(-100, 0)'), []);
});

test('a parameter without documented bounds is never out of range', () => {
  assert.deepEqual(codes('FixMove(0, 999999)'), []);
});

test('range checks can be turned off', () => {
  assert.deepEqual(codes('FixMove(101, 0)', { rangeChecks: false }), []);
});

test('malformed lines are errors', () => {
  for (const line of ['garbage', 'FixMove', 'FixMove(1, 2', 'FixMove 1, 2)', 'FixMove(1)(2)', '(1, 2)']) {
    assert.deepEqual(codes(line), ['malformed-line'], `for ${JSON.stringify(line)}`);
  }
});

test('offsets point at the offending text', () => {
  const line = 'FixMove(101, 0)';
  const issue = only(line);
  assert.equal(line.slice(issue.start, issue.end), '101');

  const nameIssue = only('  NotAnInstruction(1, 2)');
  assert.equal('  NotAnInstruction(1, 2)'.slice(nameIssue.start, nameIssue.end), 'NotAnInstruction');
});

test('parseLine classifies each kind of line', () => {
  assert.equal(parseLine('').kind, 'empty');
  assert.equal(parseLine('   ').kind, 'empty');
  assert.equal(parseLine('// note').kind, 'comment');
  assert.equal(parseLine('FixStop()').kind, 'call');
  assert.equal(parseLine('nope').kind, 'malformed');
  assert.deepEqual(parseLine('FixStop()').args, []);
});

test('analyzeDocument reports zero-based line numbers', () => {
  const doc = [
    '// Program generated by RoboDK',
    'FixMove(0, 0)',
    '',
    'FixCount(2.5)',
    'NotAnInstruction(1, 2)'
  ].join('\n');

  const issues = analyzeDocument(doc, set);
  assert.deepEqual(issues.map((i) => [i.line, i.code]), [
    [3, 'expected-int'],
    [4, 'unknown-instruction']
  ]);
});

test('analyzeDocument handles CRLF line endings', () => {
  const issues = analyzeDocument('FixStop()\r\nFixCount(2.5)\r\n', set);
  assert.deepEqual(issues.map((i) => i.line), [1]);
});

test('an optional parameter makes the argument count a range', () => {
  assert.deepEqual(codes('FixOptional()'), []);
  assert.deepEqual(codes('FixOptional(1)'), []);
  assert.deepEqual(codes('FixOptional(1, 2)'), ['arg-count']);
  assert.match(only('FixOptional(1, 2)').message, /takes 0 to 1 arguments/);
  assert.deepEqual(codes('FixOptional(7)'), ['expected-bool']);
});

test('a string parameter takes a bare word or a quoted string', () => {
  // The manual documents no quoting rule and real MecaPortal files use both
  // forms, so neither may be rejected.
  assert.deepEqual(codes('FixName(Program_01)'), []);
  assert.deepEqual(codes('FixName(1)'), []);
  assert.deepEqual(codes('FixName("my-program")'), []);
  assert.deepEqual(codes("FixName('my-program')"), []);
  assert.deepEqual(codes('FixName("with space, and comma")'), []);
});

test('a bare word carrying punctuation must be quoted', () => {
  const issue = only('FixName(my-program)');
  assert.equal(issue.code, 'not-a-value');
  assert.match(issue.message, /quote it/);
});

test('a quoted string is refused where a number is expected', () => {
  assert.deepEqual(codes('FixMove("1", 2)'), ['not-a-number']);
});

test('an unclosed quote is reported on its own', () => {
  const issue = only('FixName("never closed');
  assert.equal(issue.code, 'unterminated-string');
  assert.equal(issue.severity, 'error');
});

test('quotes hide commas and comment markers from the parser', () => {
  assert.deepEqual(codes('FixName("a, b")'), [], 'the comma is not an argument separator');
  assert.deepEqual(codes('FixName("http://example")'), [], 'the // is not a comment');
  assert.deepEqual(parseLine('FixName("a, b")').args.length, 1);
  assert.equal(parseLine('FixName("x") // note').args[0].text, '"x"');
});

test('the silent dash prefix is accepted', () => {
  // The manual documents "-MoveLin(208,50,40,0,0,90)": a leading dash asks the
  // robot to run the command without logging it.
  assert.deepEqual(codes('-FixStop()'), []);
  assert.deepEqual(codes('-FixMove(1, 2)'), []);
  assert.equal(parseLine('-FixStop()').silent, true);
  assert.equal(parseLine('FixStop()').silent, false);
});

test('the dash does not shift the reported offsets', () => {
  const line = '-FixMove(101, 0)';
  const issue = only(line);
  assert.equal(line.slice(issue.start, issue.end), '101');
});

test('a code-or-name list takes codes or names, never both', () => {
  assert.deepEqual(codes('FixData(2200, 2201, 2202)'), []);
  assert.deepEqual(codes('FixData(TargetCartPos, TargetJointPos)'), []);
  assert.deepEqual(codes('FixData(All)'), []);

  const mixed = only('FixData(2200, TargetCartPos)');
  assert.equal(mixed.code, 'mixed-argument-kinds');
  assert.equal(mixed.severity, 'error');
  assert.equal('FixData(2200, TargetCartPos)'.slice(mixed.start, mixed.end), 'TargetCartPos');
});

test('a code must be a whole number', () => {
  assert.deepEqual(codes('FixData(2200.5)'), ['expected-int']);
});

test('an empty argument is an error', () => {
  assert.deepEqual(codes('FixName()'), ['arg-count']);
  assert.deepEqual(codes('FixMove(1, )'), ['empty-argument']);
});

test('a value set warns instead of imposing a range', () => {
  assert.deepEqual(codes('FixConf(-1)'), []);
  assert.deepEqual(codes('FixConf(1)'), []);
  const issue = only('FixConf(0)');
  assert.equal(issue.code, 'invalid-value');
  assert.equal(issue.severity, 'warning');
  assert.match(issue.message, /should be -1 or 1/);
  assert.deepEqual(codes('FixConf(0)', { rangeChecks: false }), []);
});
