'use strict';

const test = require('node:test');
const assert = require('node:assert');
const path = require('path');

const { loadInstructionSet } = require('../src/instructions');
const { parseLine, parseDocument, argumentKind, analyzeLine, analyzeDocument } = require('../src/analyze');

const set = loadInstructionSet(path.join(__dirname, 'fixtures', 'instructions.fixture.json'));

/** Analyze one line and return its issue codes, in order. */
const codes = (line, options) => analyzeLine(line, set, options).map((i) => i.code);
const only = (line, options) => {
  const issues = analyzeLine(line, set, options);
  assert.equal(issues.length, 1, `expected exactly one issue for ${JSON.stringify(line)}`);
  return issues[0];
};

test('accepts a well-formed call', () => {
  assert.deepEqual(codes('FixMove(10, 20)'), []);
  assert.deepEqual(codes('FixMove(10,20)'), []);
  assert.deepEqual(codes('  FixMove( -12.5 , 0 )  '), []);
});

test('accepts an instruction that takes no arguments', () => {
  assert.deepEqual(codes('FixStop()'), []);
});

test('blank lines produce no issues', () => {
  assert.deepEqual(codes(''), []);
  assert.deepEqual(codes('    '), []);
  assert.deepEqual(codes('\t'), []);
});

test('comments produce no issues', () => {
  assert.deepEqual(codes('// Program generated by RoboDK'), []);
  assert.deepEqual(codes('   // indented comment'), []);
  assert.deepEqual(codes('FixStop() // trailing comment'), []);
});

test('unknown instruction is a warning, never an error', () => {
  const issue = only('NotAnInstruction(1)');
  assert.equal(issue.code, 'unknown-instruction');
  assert.equal(issue.severity, 'warning');
  assert.match(issue.message, /0\.0-fixture/);
});

test('unknown instruction can be silenced', () => {
  assert.deepEqual(codes('NotAnInstruction(1)', { unknownInstruction: 'off' }), []);
});

test('a name differing only by case is accepted, not flagged', () => {
  // The robot resolves instruction names regardless of case: SetWRF and SetWrf
  // both work, so neither may be reported as a problem.
  assert.deepEqual(codes('fixmove(1, 2)'), []);
  assert.deepEqual(codes('FIXMOVE(1, 2)'), []);
  assert.deepEqual(codes('FixMOVE(1, 2)'), []);
});

test('a case variant is still validated against its instruction', () => {
  assert.deepEqual(codes('fixmove(1)'), ['arg-count']);
  assert.deepEqual(codes('FIXCOUNT(2.5)'), ['expected-int']);
  assert.deepEqual(codes('fixmove(101, 0)'), ['out-of-range']);
});

test('wrong argument count is an error that shows the signature', () => {
  const tooFew = only('FixMove(1)');
  assert.equal(tooFew.code, 'arg-count');
  assert.equal(tooFew.severity, 'error');
  assert.match(tooFew.message, /takes 2 arguments, got 1/);
  assert.match(tooFew.message, /FixMove\(x: number mm, y: number mm\)/);

  assert.deepEqual(codes('FixMove(1, 2, 3)'), ['arg-count']);
  assert.deepEqual(codes('FixStop(1)'), ['arg-count']);
  assert.match(only('FixCount()').message, /takes 1 argument,/);
});

test('non-numeric argument is an error', () => {
  const issue = only('FixMove(abc, 2)');
  assert.equal(issue.code, 'not-a-number');
  assert.equal(issue.severity, 'error');
});

test('scientific notation is rejected with its own message', () => {
  const issue = only('FixMove(1e3, 2)');
  assert.equal(issue.code, 'scientific-notation');
  assert.equal(issue.severity, 'error');
});

test('a parameter typed int rejects a fractional value', () => {
  const issue = only('FixCount(2.5)');
  assert.equal(issue.code, 'expected-int');
  assert.equal(issue.severity, 'error');
  // A whole number written with a decimal point is still an integer.
  assert.deepEqual(codes('FixCount(2.0)'), []);
});

test('a parameter typed bool accepts only 0 and 1', () => {
  assert.deepEqual(codes('FixEnable(0)'), []);
  assert.deepEqual(codes('FixEnable(1)'), []);
  assert.deepEqual(codes('FixEnable(2)'), ['expected-bool']);
});

test('exceeding min or max is a warning, not an error', () => {
  const over = only('FixMove(101, 0)');
  assert.equal(over.code, 'out-of-range');
  assert.equal(over.severity, 'warning');
  assert.match(over.message, /maximum 100 mm/);

  const under = only('FixMove(-101, 0)');
  assert.equal(under.code, 'out-of-range');
  assert.match(under.message, /minimum -100 mm/);

  assert.deepEqual(codes('FixMove(100, 0)'), []);
  assert.deepEqual(codes('FixMove(-100, 0)'), []);
});

test('a parameter without documented bounds is never out of range', () => {
  assert.deepEqual(codes('FixMove(0, 999999)'), []);
});

test('range checks can be turned off', () => {
  assert.deepEqual(codes('FixMove(101, 0)', { rangeChecks: false }), []);
});

test('malformed lines are errors', () => {
  for (const line of ['garbage', 'FixMove', 'FixMove(1, 2', 'FixMove 1, 2)', 'FixMove(1)(2)', '(1, 2)']) {
    assert.deepEqual(codes(line), ['malformed-line'], `for ${JSON.stringify(line)}`);
  }
});

test('offsets point at the offending text', () => {
  const line = 'FixMove(101, 0)';
  const issue = only(line);
  assert.equal(line.slice(issue.start, issue.end), '101');

  const nameIssue = only('  NotAnInstruction(1, 2)');
  assert.equal('  NotAnInstruction(1, 2)'.slice(nameIssue.start, nameIssue.end), 'NotAnInstruction');
});

test('parseLine classifies each kind of line', () => {
  assert.equal(parseLine('').kind, 'empty');
  assert.equal(parseLine('   ').kind, 'empty');
  assert.equal(parseLine('// note').kind, 'comment');
  assert.equal(parseLine('FixStop()').kind, 'call');
  assert.equal(parseLine('nope').kind, 'malformed');
  assert.deepEqual(parseLine('FixStop()').args, []);
});

test('analyzeDocument reports zero-based line numbers', () => {
  const doc = [
    '// Program generated by RoboDK',
    'FixMove(0, 0)',
    '',
    'FixCount(2.5)',
    'NotAnInstruction(1, 2)'
  ].join('\n');

  const issues = analyzeDocument(doc, set);
  assert.deepEqual(issues.map((i) => [i.line, i.code]), [
    [3, 'expected-int'],
    [4, 'unknown-instruction']
  ]);
});

test('analyzeDocument handles CRLF line endings', () => {
  const issues = analyzeDocument('FixStop()\r\nFixCount(2.5)\r\n', set);
  assert.deepEqual(issues.map((i) => i.line), [1]);
});

test('an optional parameter makes the argument count a range', () => {
  assert.deepEqual(codes('FixOptional()'), []);
  assert.deepEqual(codes('FixOptional(1)'), []);
  assert.deepEqual(codes('FixOptional(1, 2)'), ['arg-count']);
  assert.match(only('FixOptional(1, 2)').message, /takes 0 to 1 arguments/);
  assert.deepEqual(codes('FixOptional(7)'), ['expected-bool']);
});

test('a string parameter takes a bare word or a quoted string', () => {
  // The manual documents no quoting rule and real MecaPortal files use both
  // forms, so neither may be rejected.
  assert.deepEqual(codes('FixName(Program_01)'), []);
  assert.deepEqual(codes('FixName(1)'), []);
  assert.deepEqual(codes('FixName("my-program")'), []);
  assert.deepEqual(codes("FixName('my-program')"), []);
  assert.deepEqual(codes('FixName("with space, and comma")'), []);
});

test('a bare word carrying punctuation must be quoted', () => {
  const issue = only('FixName(my-program)');
  assert.equal(issue.code, 'not-a-value');
  assert.match(issue.message, /quote it/);
});

test('a quoted string is refused where a number is expected', () => {
  assert.deepEqual(codes('FixMove("1", 2)'), ['not-a-number']);
});

test('an unclosed quote is reported on its own', () => {
  const issue = only('FixName("never closed');
  assert.equal(issue.code, 'unterminated-string');
  assert.equal(issue.severity, 'error');
});

test('quotes hide commas and comment markers from the parser', () => {
  assert.deepEqual(codes('FixName("a, b")'), [], 'the comma is not an argument separator');
  assert.deepEqual(codes('FixName("http://example")'), [], 'the // is not a comment');
  assert.deepEqual(parseLine('FixName("a, b")').args.length, 1);
  assert.equal(parseLine('FixName("x") // note').args[0].text, '"x"');
});

test('the silent dash prefix is accepted', () => {
  // The manual documents "-MoveLin(208,50,40,0,0,90)": a leading dash asks the
  // robot to run the command without logging it.
  assert.deepEqual(codes('-FixStop()'), []);
  assert.deepEqual(codes('-FixMove(1, 2)'), []);
  assert.equal(parseLine('-FixStop()').silent, true);
  assert.equal(parseLine('FixStop()').silent, false);
});

test('the dash does not shift the reported offsets', () => {
  const line = '-FixMove(101, 0)';
  const issue = only(line);
  assert.equal(line.slice(issue.start, issue.end), '101');
});

test('a code-or-name list takes codes or names, never both', () => {
  assert.deepEqual(codes('FixData(2200, 2201, 2202)'), []);
  assert.deepEqual(codes('FixData(TargetCartPos, TargetJointPos)'), []);
  assert.deepEqual(codes('FixData(All)'), []);

  const mixed = only('FixData(2200, TargetCartPos)');
  assert.equal(mixed.code, 'mixed-argument-kinds');
  assert.equal(mixed.severity, 'error');
  assert.equal('FixData(2200, TargetCartPos)'.slice(mixed.start, mixed.end), 'TargetCartPos');
});

test('a code must be a whole number', () => {
  assert.deepEqual(codes('FixData(2200.5)'), ['expected-int']);
});

test('an empty argument is an error', () => {
  assert.deepEqual(codes('FixName()'), ['arg-count']);
  assert.deepEqual(codes('FixMove(1, )'), ['empty-argument']);
});

test('a value set warns instead of imposing a range', () => {
  assert.deepEqual(codes('FixConf(-1)'), []);
  assert.deepEqual(codes('FixConf(1)'), []);
  const issue = only('FixConf(0)');
  assert.equal(issue.code, 'invalid-value');
  assert.equal(issue.severity, 'warning');
  assert.match(issue.message, /should be -1 or 1/);
  assert.deepEqual(codes('FixConf(0)', { rangeChecks: false }), []);
});

test('a block comment on one line is ignored', () => {
  assert.deepEqual(codes('/* a note */'), []);
  assert.deepEqual(codes('FixStop() /* trailing */'), []);
  assert.deepEqual(codes('/* leading */ FixStop()'), []);
  assert.deepEqual(codes('FixMove(/* x */ 1, 2)'), []);
});

test('a block comment marker inside quotes is not a comment', () => {
  assert.deepEqual(codes('FixName("/* not a comment */")'), []);
  assert.equal(parseLine('FixName("/* x */")').args[0].text, '"/* x */"');
});

test('a block comment carries across lines', () => {
  const parsed = parseDocument(['/* opens', 'still inside', 'closes */', 'FixStop()'].join('\n'));
  assert.deepEqual(parsed.map((p) => p.kind), ['comment', 'comment', 'comment', 'call']);
  assert.deepEqual(parsed.map((p) => p.endsInComment), [true, true, false, false]);
});

test('code resumes on the line that closes the block', () => {
  const parsed = parseDocument(['/* opens', 'closes */ FixStop()'].join('\n'));
  assert.equal(parsed[1].kind, 'call');
  assert.equal(parsed[1].name, 'FixStop');
});

test('a commented-out call is not validated', () => {
  const doc = ['/*', 'FixMove(1)', 'FixCount(2.5)', '*/', 'FixStop()'].join('\n');
  assert.deepEqual(analyzeDocument(doc, set), []);
});

test('a block comment left open is reported where it opens', () => {
  const doc = ['FixStop()', 'SetUp /* opens here', 'FixMove(1)'].join('\n');
  const issues = analyzeDocument(doc, set);
  const unterminated = issues.filter((i) => i.code === 'unterminated-comment');
  assert.equal(unterminated.length, 1);
  assert.equal(unterminated[0].line, 1);
  assert.equal(unterminated[0].severity, 'error');
  assert.equal('SetUp /* opens here'.slice(unterminated[0].start, unterminated[0].end), '/*');
});

test('a closed block comment is never reported as unterminated', () => {
  const doc = ['/* a', 'b */', 'FixStop()', '/* c */'].join('\n');
  assert.deepEqual(analyzeDocument(doc, set).map((i) => i.code), []);
});

test('block comments preserve the offsets of the code around them', () => {
  const line = '/* skip */ FixMove(101, 0)';
  const issue = only(line);
  assert.equal(line.slice(issue.start, issue.end), '101');
});

test('a variable stands in for any value', () => {
  // The manual: "Variables can be used as values when calling robot commands."
  // Their type lives on the robot, so nothing about them can be checked here.
  assert.deepEqual(codes('FixMove(vars.x, vars.y)'), []);
  assert.deepEqual(codes('FixMove(vars.myGroup.mySubgroup.x, 0)'), []);
  assert.deepEqual(codes('FixCount(vars.n)'), [], 'no int check on a variable');
  assert.deepEqual(codes('FixMove(vars.x, 0)', { rangeChecks: true }), [], 'no range check either');
  assert.deepEqual(codes('FixEnable(vars.e)'), []);
});

test('an unrolled array variable suspends the argument count', () => {
  // MoveJoints(*vars.myGroup.myJointPos) writes one argument for six.
  assert.deepEqual(codes('FixMove(*vars.myJointPos)'), []);
  assert.deepEqual(codes('FixMove(*vars.a, *vars.b)'), []);
  assert.deepEqual(codes('FixMove(1, *vars.rest)'), []);
  assert.deepEqual(codes('FixStop(*vars.anything)'), []);
});

test('an unrolled call still rejects a malformed argument', () => {
  assert.deepEqual(codes('FixMove(*vars.a, b-c)'), ['not-a-value']);
});

test('only the vars. prefix makes a variable', () => {
  assert.deepEqual(codes('FixMove(variables.x, 0)'), ['not-a-number']);
  assert.deepEqual(codes('FixMove(vars, 0)'), ['not-a-number'], 'vars alone is a bare name');
});

test('argumentKind tells the value flavours apart', () => {
  assert.equal(argumentKind('vars.a.b'), 'variable');
  assert.equal(argumentKind('*vars.a.b'), 'unrolled');
  assert.equal(argumentKind('[1, 2, 3]'), 'array');
  assert.equal(argumentKind('true'), 'boolean');
  assert.equal(argumentKind('"text"'), 'string');
  assert.equal(argumentKind('12.5'), 'number');
  assert.equal(argumentKind('Name'), 'name');
  assert.equal(argumentKind('a-b'), 'invalid');
});

test('an array literal is one argument, not several', () => {
  assert.deepEqual(parseLine('FixVar(v, [1, 2, 3])').args.map((a) => a.text), ['v', '[1, 2, 3]']);
  assert.deepEqual(parseLine('FixVar(v, [[1, 2], [3]])').args.length, 2, 'nesting is respected');
  assert.deepEqual(codes('FixVar(v, [1, 2, 3])'), []);
  assert.deepEqual(codes('FixVar(v, [1, 2, 3, 4, 5, 6])'), []);
});

test('a json parameter takes any basic JSON value', () => {
  assert.deepEqual(codes('FixVar(v, 12.5)'), []);
  assert.deepEqual(codes('FixVar(v, true)'), []);
  assert.deepEqual(codes('FixVar(v, false)'), []);
  assert.deepEqual(codes('FixVar(v, "some text")'), []);
  assert.deepEqual(codes('FixVar(v, [1, 2])'), []);
  assert.deepEqual(codes('FixVar(v, vars.other)'), []);
  assert.deepEqual(codes('FixVar(v, a-b)'), ['not-a-value']);
});

test('an array is refused where a number is expected', () => {
  const issue = only('FixMove([1, 2], 0)');
  assert.equal(issue.code, 'unexpected-array');
  assert.equal(issue.severity, 'error');
});

test('a JSON boolean is refused where a number is expected', () => {
  assert.deepEqual(codes('FixMove(true, 0)'), ['not-a-number']);
});

test('a variable does not trip the code-or-name uniformity rule', () => {
  assert.deepEqual(codes('FixData(vars.a, 2200)'), []);
  assert.deepEqual(codes('FixData(vars.a, TargetCartPos)'), []);
  assert.deepEqual(codes('FixData(2200, TargetCartPos)'), ['mixed-argument-kinds']);
});
